// Data shapes exchanged between the backend, the Mini App and the admin panel.
import type { PayoutMethod, WithdrawalStatus } from './payout.js';

export interface MeDto {
  user: {
    id: number;
    telegramId: number;
    username: string | null;
    firstName: string;
    lastName: string | null;
    photoUrl: string | null;
  };
  /** Spendable balance, micro-USDT. */
  availableMicro: number;
  /** Locked in withdrawals that are not finished yet, micro-USDT. */
  frozenMicro: number;
  blocked: boolean;
  supportUsername: string;
}

export interface CreateWithdrawalRequest {
  method: PayoutMethod;
  amountRub: number;
  phone?: string;
  bankId?: string;
  cardNumber?: string;
  /** Random id generated by the client, makes a repeated submit harmless. */
  requestId: string;
  platform?: string;
  acceptedTerms: true;
}

/** Withdrawal as the user sees it. */
export interface WithdrawalDto {
  id: number;
  method: PayoutMethod;
  status: WithdrawalStatus;
  amountRub: number;
  amountMicro: number;
  rate: number;
  /** "+7 912 345-67-89 · Сбербанк" or "МИР •• 9010". */
  destination: string;
  createdAt: number;
  sentAt: number | null;
  confirmDeadline: number | null;
  finishedAt: number | null;
  confirmedBy: 'user' | 'auto' | 'admin' | null;
  rejectReason: string | null;
  serverNow: number;
}

export type NotificationType = 'confirm_receipt' | 'contact_support' | 'withdrawal_completed' | 'withdrawal_rejected';

export interface NotificationDto {
  id: number;
  type: NotificationType;
  withdrawalId: number | null;
  createdAt: number;
}

// ---------- Admin ----------

export interface AdminUserDto {
  id: number;
  telegramId: number;
  username: string | null;
  firstName: string;
  lastName: string | null;
  photoUrl: string | null;
  languageCode: string | null;
  createdAt: number;
  lastSeenAt: number;
  blocked: boolean;
  missedConfirmations: number;
  availableMicro: number;
  frozenMicro: number;
  depositAddresses: { chain: string; address: string; createdAt: number }[];
  stats: {
    depositedMicro: number;
    withdrawnRub: number;
    withdrawnMicro: number;
    withdrawalsTotal: number;
    withdrawalsCompleted: number;
    disputes: number;
  };
}

export interface WithdrawalEventDto {
  id: number;
  at: number;
  actor: 'user' | 'admin' | 'system';
  type: string;
  data: Record<string, unknown> | null;
}

export interface AdminWithdrawalListItem {
  id: number;
  status: WithdrawalStatus;
  method: PayoutMethod;
  amountRub: number;
  amountMicro: number;
  destination: string;
  createdAt: number;
  confirmDeadline: number | null;
  user: { id: number; username: string | null; firstName: string };
}

export interface AdminWithdrawalDto extends AdminWithdrawalListItem {
  phone: string | null;
  bankId: string | null;
  bankName: string | null;
  cardNumber: string | null;
  cardBrand: string | null;
  rate: number;
  exchangeBid: number | null;
  balanceBeforeMicro: number;
  sentAt: number | null;
  finishedAt: number | null;
  confirmedBy: 'user' | 'auto' | 'admin' | null;
  rejectReason: string | null;
  contactRequestedAt: number | null;
  clientIp: string | null;
  userAgent: string | null;
  platform: string | null;
  events: WithdrawalEventDto[];
  userDetails: AdminUserDto;
  /** Other accounts that withdrew to the same phone or card. */
  sameDestinationUsers: { id: number; username: string | null; firstName: string; withdrawals: number }[];
  recentWithdrawals: AdminWithdrawalListItem[];
  serverNow: number;
}

export interface AdminCounts {
  pending: number;
  sent: number;
  disputed: number;
  completed: number;
  rejected: number;
}
