// Data shapes exchanged between the backend, the Mini App and the admin panel.
import type { PayoutMethod, WithdrawalStatus } from './payout.js';
import type { AuditActor, AuditType } from './audit.js';
import type { BoardSection, DealResolution, UserDealAction } from './deals.js';
import type { FineInfo, OrderStatus, ServiceKind } from './services.js';
import type { DepositRequestStatus, DepositReview } from './deposits.js';
import type { UsdtPayoutStatus } from './usdtPayout.js';

export interface MeDto {
  user: {
    id: number;
    telegramId: number;
    username: string | null;
    firstName: string;
    lastName: string | null;
    photoUrl: string | null;
  };
  /** Spendable balance, micro-USDT. */
  availableMicro: number;
  /** Locked in withdrawals that are not finished yet, micro-USDT. */
  frozenMicro: number;
  blocked: boolean;
  supportUsername: string;
  /**
   * Set while the operator requires the user to contact support: the app shows a
   * blocking screen, the bot answers with a support link, the server refuses actions.
   */
  contactLock: { since: number } | null;
  /** Time to answer on a deal ran out: everything is paused until the user answers. */
  answerLock: { withdrawalId: number; amountRub: number } | null;
  /** USDT TRC-20 withdrawal terms: the fee is added on top of the amount. */
  usdtPayout: { feeMicro: number; minMicro: number };
  /** Bot username without "@", for check links and the "@bot 10" hint. */
  botUsername: string;
  /** Profile numbers. An exchange is a completed USDT → RUB withdrawal. */
  stats: { exchanges: number; exchangedRub: number; memberSince: number };
}

/** Deposits: USDT on TRON (TRC-20) only. */
export interface DepositInfoDto {
  token: 'USDT';
  network: 'TRC20';
  networkName: string;
  /** false when no deposit addresses are configured in the admin panel. */
  enabled: boolean;
  /** The open request, or the last one if it ended less than a minute ago. */
  request: DepositRequestDto | null;
  minDepositMicro: number;
  confirmations: number;
  /** true in the standalone demo: the address is a fake placeholder. */
  demo?: boolean;
}

export interface DepositRequestDto {
  id: number;
  address: string;
  status: DepositRequestStatus;
  createdAt: number;
  expiresAt: number;
  endedAt: number | null;
  /** USDT seen for this request so far (confirmed or not). */
  receivedMicro: number;
  /** Of that, already on the balance. */
  creditedMicro: number;
  serverNow: number;
}

/** 409 pool_busy carries this: every address is lent out. */
export interface DepositPoolBusyDto {
  error: 'pool_busy';
  message: string;
  retryAt: number;
}

export interface CreateWithdrawalRequest {
  method: PayoutMethod;
  amountRub: number;
  phone?: string;
  bankId?: string;
  cardNumber?: string;
  /** Random id generated by the client, makes a repeated submit harmless. */
  requestId: string;
  platform?: string;
  acceptedTerms: true;
}

/** Withdrawal as the user sees it. */
export interface WithdrawalDto {
  id: number;
  method: PayoutMethod;
  status: WithdrawalStatus;
  amountRub: number;
  amountMicro: number;
  rate: number;
  /** "+7 912 345-67-89 · Сбербанк" or "МИР •• 9010". */
  destination: string;
  createdAt: number;
  /** When the executor entered the deal: reminders and the answer window count from here. */
  enteredAt: number | null;
  /** What the user can press right now (computed on the server clock). */
  actions: UserDealAction[];
  /** Latest answer of the user. */
  userDecision: 'received' | 'not_received' | 'other_amount' | null;
  reportedRub: number | null;
  /** Rubles the deal was finally settled for (after a correction it differs from amountRub). */
  finalRub: number | null;
  debitedMicro: number | null;
  refundedMicro: number | null;
  finishedAt: number | null;
  resolution: DealResolution | null;
  serverNow: number;
}

export type NotificationType =
  | 'deal_reminder'
  | 'deal_completed'
  | 'deal_cancelled'
  | 'deal_corrected'
  | 'support_lock'
  | 'obligation_repaid'
  | 'transfer_received'
  | 'check_claimed'
  | 'order_paid'
  | 'order_rejected'
  | 'order_clarify'
  | 'deposit_credited'
  | 'usdt_payout_sent'
  | 'usdt_payout_rejected';

export interface NotificationDto {
  id: number;
  type: NotificationType;
  withdrawalId: number | null;
  /** transfer_received: what arrived and from whom. */
  transfer?: TransferDto | null;
  /** check_claimed: the sender's check that was just activated. */
  check?: CheckDto | null;
  /** order_*: the service order whose status changed. */
  order?: ServiceOrderDto | null;
  /** deposit_credited: the deposit that just landed on the balance. */
  deposit?: DepositDto | null;
  /** usdt_payout_sent / usdt_payout_rejected. */
  usdtPayout?: UsdtPayoutDto | null;
  /** obligation_repaid: what was held back and why. */
  deduction?: DeductionDto | null;
  createdAt: number;
}

/** A hold of USDT the user learns about only when it happens. */
export interface DeductionDto {
  id: number;
  amountMicro: number;
  reason: string;
  createdAt: number;
}

/**
 * pending   seen in the chain, waiting for an irreversible (solidified) block
 * credited  on the balance
 * below_min smaller than the minimum, not credited (support can credit by hand)
 * held      AML check flagged the sender or could not run: an operator decides
 * rejected  operator refused to credit
 */
export type DepositStatus = 'pending' | 'credited' | 'below_min' | 'held' | 'rejected';

export interface DepositDto {
  id: number;
  status: DepositStatus;
  amountMicro: number;
  network: 'TRC20';
  txId: string;
  fromAddress: string | null;
  createdAt: number;
  creditedAt: number | null;
}

// ---------- Transfers and checks ----------

export interface PersonDto {
  username: string | null;
  firstName: string;
  photoUrl?: string | null;
}

export interface TransferDto {
  id: number;
  direction: 'in' | 'out';
  /** direct = by username, check = someone activated a check. */
  kind: 'direct' | 'check';
  amountMicro: number;
  counterparty: PersonDto;
  comment: string | null;
  createdAt: number;
}

export type CheckStatus = 'active' | 'claimed' | 'cancelled';

export interface CheckDto {
  id: number;
  code: string;
  amountMicro: number;
  comment: string | null;
  status: CheckStatus;
  createdAt: number;
  claimedAt: number | null;
  claimedBy: PersonDto | null;
  /** https://t.me/<bot>?start=c_<code> */
  link: string;
}

export interface SendTransferRequest {
  username: string;
  amount: string;
  comment?: string;
  requestId: string;
}

export interface CreateCheckRequest {
  amount: string;
  comment?: string;
  requestId: string;
}

// ---------- Services (fines, parking, Steam) ----------

export interface ServicesConfigDto {
  discountPercent: number;
  /** RUB per 1 USDT for services, already including the discount. */
  serviceRate: number;
  /** false until a fines data provider is configured: the user types the amount from the ruling. */
  fineLookupAvailable: boolean;
  steam: { minRub: number; maxRub: number };
  parking: { minRub: number; maxRub: number };
}

export type FineLookupDto = { found: true; fine: FineInfo } | { found: false; manual: boolean; message: string };

export interface CreateOrderRequest {
  kind: ServiceKind;
  requestId: string;
  /** fine */
  uin?: string;
  /** fine without a data provider, parking: rubles to pay */
  amountRub?: number;
  /** parking: phone of the parking account */
  phone?: string;
  /** steam */
  steamLogin?: string;
  /** steam: USDT the user spends */
  amountUsdt?: string;
  acceptedTerms: true;
}

export interface ServiceOrderDto {
  id: number;
  kind: ServiceKind;
  status: OrderStatus;
  amountRub: number;
  amountMicro: number;
  rate: number;
  discountPercent: number;
  /** How much the user saved vs. the exchange price, in rubles. */
  benefitRub: number;
  /** "УИН 1881…", "+7 912 …", "Логин steam_user" */
  target: string;
  fine: FineInfo | null;
  /** Operator's question when status is "clarify". */
  clarifyMessage: string | null;
  rejectReason: string | null;
  createdAt: number;
  finishedAt: number | null;
}

export type HistoryItem =
  | { type: 'withdrawal'; at: number; withdrawal: WithdrawalDto }
  | { type: 'order'; at: number; order: ServiceOrderDto }
  | { type: 'transfer'; at: number; transfer: TransferDto }
  | { type: 'check'; at: number; check: CheckDto }
  | { type: 'deposit'; at: number; deposit: DepositDto }
  | { type: 'deduction'; at: number; deduction: DeductionDto }
  | { type: 'usdt_payout'; at: number; usdtPayout: UsdtPayoutDto };

// ---------- USDT TRC-20 withdrawals ----------

export interface CreateUsdtPayoutRequest {
  address: string;
  /** What the recipient gets, e.g. "25.5". The fee is charged on top. */
  amount: string;
  /** Random id generated by the client, makes a repeated submit harmless. */
  requestId: string;
  acceptedTerms: true;
}

export interface UsdtPayoutDto {
  id: number;
  address: string;
  amountMicro: number;
  feeMicro: number;
  /** amount + fee, frozen while the request is open. */
  totalMicro: number;
  status: UsdtPayoutStatus;
  txId: string | null;
  rejectReason: string | null;
  createdAt: number;
  finishedAt: number | null;
}

export interface AdminUsdtPayoutDto extends UsdtPayoutDto {
  user: AdminUserRef;
  amlDecision: 'clear' | 'review' | 'reject' | null;
  amlSignals: { source: string; hit: boolean; error?: string; detail?: string }[];
  adminNote: string | null;
  /** Earlier completed withdrawals of this user to the same address. */
  sameAddressBefore: number;
  /** Balance at the moment of the request, before freezing. */
  balanceBeforeMicro: number;
}

// ---------- Admin statistics ----------

export interface AdminStatsPeriod {
  label: string;
  from: number;
  to: number;
  /** Ruble payouts that reached the user (confirmed or closed). */
  payoutRub: number;
  payoutMicro: number;
  payoutCount: number;
  /** Different users who got a ruble payout. */
  payoutUsers: number;
  /** From request to payout, minutes. */
  avgDealMinutes: number | null;
  /** From "entered the deal" to the user's "received", minutes. */
  avgResponseMinutes: number | null;
  dealsCreated: number;
  dealsCancelled: number;
  usdtPayoutCount: number;
  usdtPayoutMicro: number;
  usdtFeesMicro: number;
  depositCount: number;
  depositMicro: number;
  ordersCount: number;
  ordersRub: number;
  transferCount: number;
  transferMicro: number;
  newUsers: number;
}

export interface AdminStatsDto {
  serverNow: number;
  /** Today, yesterday, 7 days, 30 days (Moscow time). */
  periods: AdminStatsPeriod[];
  /** Ruble payouts per day, last 14 days, oldest first. */
  days: { day: number; payoutRub: number; payoutCount: number }[];
  now: {
    activeDeals: number;
    dealsByStatus: Record<string, number>;
    usdtPayoutsWaiting: number;
    depositsHeld: number;
    usersTotal: number;
    /** All users' spendable balances: what the service owes. */
    availableMicro: number;
    frozenMicro: number;
  };
  /** Biggest ruble payout users of the last 7 days. */
  topUsers: { id: number; username: string | null; firstName: string; deals: number; rub: number }[];
}

export interface AdminUsdtPayoutCounts {
  new: number;
  sent: number;
  rejected: number;
}

// ---------- Admin ----------

export interface AdminUserDto {
  id: number;
  telegramId: number;
  username: string | null;
  firstName: string;
  lastName: string | null;
  photoUrl: string | null;
  languageCode: string | null;
  createdAt: number;
  lastSeenAt: number;
  blocked: boolean;
  missedConfirmations: number;
  supportLockedAt: number | null;
  botBlockedAt: number | null;
  obligationsLeftMicro: number;
  availableMicro: number;
  frozenMicro: number;
  /** Wallets this user topped up from (credited deposits). */
  senderWallets: { address: string; deposits: number; lastAt: number }[];
  stats: {
    depositedMicro: number;
    withdrawnRub: number;
    withdrawnMicro: number;
    withdrawalsTotal: number;
    withdrawalsCompleted: number;
    disputes: number;
    transfersInMicro: number;
    transfersOutMicro: number;
    activeChecksMicro: number;
  };
}

export interface WithdrawalEventDto {
  id: number;
  at: number;
  actor: 'user' | 'admin' | 'system';
  type: string;
  data: Record<string, unknown> | null;
}

export interface AdminDealUser {
  id: number;
  username: string | null;
  firstName: string;
  telegramId: number;
  supportLocked: boolean;
  botBlocked: boolean;
}

export interface AdminWithdrawalListItem {
  id: number;
  status: WithdrawalStatus;
  section: BoardSection | null;
  method: PayoutMethod;
  amountRub: number;
  amountMicro: number;
  destination: string;
  /** Phone or card number as the platform needs it: what to disable after "entered". */
  requisite: string;
  /** NSPK bank id for SBP payouts, to show the bank logo. */
  bankId: string | null;
  bankName: string | null;
  createdAt: number;
  takenAt: number | null;
  enteredAt: number | null;
  requisiteOffAt: number | null;
  remindersSent: number;
  nextReminderAt: number | null;
  /** When the deal turns "inactive" if the user stays silent. */
  inactiveAt: number | null;
  /** When the external platform drops the deal (15 min after the executor entered). */
  platformDeadline: number | null;
  userDecision: 'received' | 'not_received' | 'other_amount' | null;
  userDecidedAt: number | null;
  /** Last "money has not arrived yet" press: the user is there and reacting, the deal is unchanged. */
  userActiveAt: number | null;
  reportedRub: number | null;
  externalId: string | null;
  resolution: DealResolution | null;
  finalRub: number | null;
  finishedAt: number | null;
  user: AdminDealUser;
}

export interface AdminReminderDto {
  n: number;
  at: number;
  delivered: boolean;
  error: string | null;
  /** The user pressed "not yet" while this reminder was the latest one. */
  reactedAt: number | null;
}

export interface AdminWithdrawalDto extends AdminWithdrawalListItem {
  phone: string | null;
  cardNumber: string | null;
  cardBrand: string | null;
  rate: number;
  /** Rapira price the applied rate was derived from. */
  exchangeRate: number | null;
  balanceBeforeMicro: number;
  debitedMicro: number | null;
  refundedMicro: number | null;
  userConfirmedAt: number | null;
  inactiveSince: number | null;
  /** For a correction: what accepting it would do, using the user's current balance. */
  correction: {
    reportedRub: number;
    correctedMicro: number;
    refundMicro: number;
    extraMicro: number;
    fromAvailableMicro: number;
    shortageMicro: number;
  } | null;
  clientIp: string | null;
  userAgent: string | null;
  platform: string | null;
  reminders: AdminReminderDto[];
  events: AdminAuditItem[];
  userDetails: AdminUserDto;
  /** Other accounts that withdrew to the same phone or card. */
  sameDestinationUsers: { id: number; username: string | null; firstName: string; withdrawals: number }[];
  recentWithdrawals: AdminWithdrawalListItem[];
  obligations: AdminObligationDto[];
  serverNow: number;
}

export interface AdminBoardDto {
  items: AdminWithdrawalListItem[];
  counts: Record<BoardSection, number>;
  serverNow: number;
}

export interface ArchiveQuery {
  q?: string;
  status?: 'completed' | 'cancelled' | '';
  resolution?: DealResolution | '';
  method?: PayoutMethod | '';
  from?: number;
  to?: number;
  offset?: number;
}

export interface AdminAuditItem {
  id: number;
  at: number;
  actor: AuditActor;
  type: AuditType;
  label: string;
  userId: number | null;
  username: string | null;
  firstName: string | null;
  withdrawalId: number | null;
  obligationId: number | null;
  amountMicro: number | null;
  amountRub: number | null;
  data: Record<string, unknown> | null;
}

export interface JournalQuery {
  types?: string;
  userId?: number;
  dealId?: number;
  q?: string;
  from?: number;
  to?: number;
  before?: number;
}

export type ObligationStatus = 'active' | 'repaid' | 'written_off';

export interface AdminObligationDto {
  id: number;
  status: ObligationStatus;
  amountMicro: number;
  repaidMicro: number;
  /** Shown to the user in the hold notification. */
  publicReason: string;
  /** Internal note, never shown to the user. */
  comment: string | null;
  withdrawalId: number | null;
  createdAt: number;
  repaidAt: number | null;
  writtenOffAt: number | null;
  writeOffComment: string | null;
  user: { id: number; username: string | null; firstName: string; telegramId: number };
  /** Every hold, with its date. */
  repayments: { at: number; amountMicro: number }[];
}

export interface CreateObligationRequest {
  userId: number;
  amountUsdt: number;
  publicReason?: string;
  comment?: string;
  withdrawalId?: number | null;
}

export interface AdminUserListItem {
  id: number;
  telegramId: number;
  username: string | null;
  firstName: string;
  lastName: string | null;
  createdAt: number;
  lastSeenAt: number;
  availableMicro: number;
  frozenMicro: number;
  supportLocked: boolean;
  blocked: boolean;
  activeDeals: number;
  obligationsLeftMicro: number;
}

export interface AdminUserPageDto extends AdminUserDto {
  deals: AdminWithdrawalListItem[];
  obligations: AdminObligationDto[];
}

export interface BroadcastRequest {
  text: string;
  /** Base64 image (jpeg/png), optional. */
  photoBase64?: string | null;
  buttonText?: string | null;
  buttonUrl?: string | null;
}

export interface AdminBroadcastDto {
  id: number;
  createdAt: number;
  author: string;
  text: string;
  hasPhoto: boolean;
  buttonText: string | null;
  buttonUrl: string | null;
  status: 'sending' | 'done' | 'failed';
  total: number;
  sent: number;
  failed: number;
  blocked: number;
  finishedAt: number | null;
  errors: { userId: number; username: string | null; error: string }[];
}

export interface AdminOrderListItem {
  id: number;
  kind: ServiceKind;
  status: OrderStatus;
  amountRub: number;
  amountMicro: number;
  target: string;
  createdAt: number;
  user: { id: number; username: string | null; firstName: string; telegramId: number };
}

export interface AdminOrderDto extends AdminOrderListItem {
  rate: number;
  exchangeRate: number;
  discountPercent: number;
  benefitRub: number;
  fine: FineInfo | null;
  /** fine: whether the amount came from the data provider or was typed by the user. */
  amountSource: 'provider' | 'user' | null;
  phone: string | null;
  steamLogin: string | null;
  clarifyMessage: string | null;
  rejectReason: string | null;
  finishedAt: number | null;
  balanceBeforeMicro: number;
  clientIp: string | null;
  platform: string | null;
  events: WithdrawalEventDto[];
  userDetails: AdminUserDto;
  serverNow: number;
}

export interface AdminDepositDto {
  id: number;
  status: DepositStatus | 'failed';
  amountMicro: number;
  address: string;
  txId: string;
  fromAddress: string | null;
  amlDecision: 'clear' | 'review' | 'reject' | null;
  amlSignals: { source: string; hit: boolean; error?: string; detail?: string }[];
  blockNumber: number | null;
  createdAt: number;
  confirmedAt: number | null;
  finishedAt: number | null;
  creditedBy: 'auto' | 'admin' | null;
  adminNote: string | null;
  /** Who gets the money; null for an unidentified deposit until the operator picks someone. */
  user: AdminUserRef | null;
  review: DepositReview | null;
  /** Came after the request ended, during the quarantine. */
  late: boolean;
  requestId: number | null;
  /** Who held the address when the transfer was made. */
  issuedTo: AdminUserRef | null;
  /** Accounts this sender wallet topped up before. */
  senderUsers: AdminUserRef[];
}

export interface AdminUserRef {
  id: number;
  username: string | null;
  firstName: string;
  telegramId: number;
}

export interface AdminDepositAddressDto {
  id: number;
  address: string;
  label: string;
  enabled: boolean;
  /** The operator's own wallet: never lent out, transfers from it are ignored. */
  own: boolean;
  state: 'free' | 'busy' | 'quarantine' | 'off' | 'own';
  /** Who holds it now (busy or quarantine). */
  holder: AdminUserRef | null;
  /** When it becomes free. */
  until: number | null;
  createdAt: number;
  lastCheckedAt: number | null;
  depositsCount: number;
  receivedMicro: number;
}

/** One wallet of the pool with its live balance; null when TronGrid did not answer. */
export interface AdminWalletBalanceDto {
  id: number;
  address: string;
  label: string;
  own: boolean;
  usdtMicro: number | null;
  trxSun: number | null;
  error: string | null;
}

/** "Balance on all wallets": every pool address and own wallet, read from the chain. */
export interface AdminWalletBalancesDto {
  items: AdminWalletBalanceDto[];
  totalUsdtMicro: number;
  /** Split of the total: deposit addresses lent to users vs the operator's own wallets. */
  poolUsdtMicro: number;
  ownUsdtMicro: number;
  totalTrxSun: number;
  /** Wallets whose balance could not be read: the total is then a lower bound. */
  failed: number;
  checkedAt: number;
}

export interface AdminDepositCounts {
  held: number;
  below_min: number;
  pending: number;
  credited: number;
  rejected: number;
}

export interface AdminOrderCounts {
  pending: number;
  clarify: number;
  paid: number;
  rejected: number;
}
