// Data shapes exchanged between the backend, the Mini App and the admin panel.
import type { PayoutMethod, WithdrawalStatus } from './payout.js';

export interface MeDto {
  user: {
    id: number;
    telegramId: number;
    username: string | null;
    firstName: string;
    lastName: string | null;
    photoUrl: string | null;
  };
  /** Spendable balance, micro-USDT. */
  availableMicro: number;
  /** Locked in withdrawals that are not finished yet, micro-USDT. */
  frozenMicro: number;
  blocked: boolean;
  supportUsername: string;
  /**
   * Set while the operator asked the user to contact support and the deal is not finished:
   * the app shows a blocking screen and the server refuses money operations.
   */
  contactLock: { withdrawalId: number; amountRub: number } | null;
  /** Bot username without "@", for check links and the "@bot 10" hint. */
  botUsername: string;
}

export interface CreateWithdrawalRequest {
  method: PayoutMethod;
  amountRub: number;
  phone?: string;
  bankId?: string;
  cardNumber?: string;
  /** Random id generated by the client, makes a repeated submit harmless. */
  requestId: string;
  platform?: string;
  acceptedTerms: true;
}

/** Withdrawal as the user sees it. */
export interface WithdrawalDto {
  id: number;
  method: PayoutMethod;
  status: WithdrawalStatus;
  amountRub: number;
  amountMicro: number;
  rate: number;
  /** "+7 912 345-67-89 · Сбербанк" or "МИР •• 9010". */
  destination: string;
  createdAt: number;
  sentAt: number | null;
  confirmDeadline: number | null;
  finishedAt: number | null;
  confirmedBy: 'user' | 'auto' | 'admin' | null;
  rejectReason: string | null;
  serverNow: number;
}

export type NotificationType =
  | 'confirm_receipt'
  | 'contact_support'
  | 'withdrawal_completed'
  | 'withdrawal_rejected'
  | 'transfer_received'
  | 'check_claimed';

export interface NotificationDto {
  id: number;
  type: NotificationType;
  withdrawalId: number | null;
  /** transfer_received: what arrived and from whom. */
  transfer?: TransferDto | null;
  /** check_claimed: the sender's check that was just activated. */
  check?: CheckDto | null;
  createdAt: number;
}

// ---------- Transfers and checks ----------

export interface PersonDto {
  username: string | null;
  firstName: string;
  photoUrl?: string | null;
}

export interface TransferDto {
  id: number;
  direction: 'in' | 'out';
  /** direct = by username, check = someone activated a check. */
  kind: 'direct' | 'check';
  amountMicro: number;
  counterparty: PersonDto;
  comment: string | null;
  createdAt: number;
}

export type CheckStatus = 'active' | 'claimed' | 'cancelled';

export interface CheckDto {
  id: number;
  code: string;
  amountMicro: number;
  comment: string | null;
  status: CheckStatus;
  createdAt: number;
  claimedAt: number | null;
  claimedBy: PersonDto | null;
  /** https://t.me/<bot>?start=c_<code> */
  link: string;
}

export interface SendTransferRequest {
  username: string;
  amount: string;
  comment?: string;
  requestId: string;
}

export interface CreateCheckRequest {
  amount: string;
  comment?: string;
  requestId: string;
}

export type HistoryItem =
  | { type: 'withdrawal'; at: number; withdrawal: WithdrawalDto }
  | { type: 'transfer'; at: number; transfer: TransferDto }
  | { type: 'check'; at: number; check: CheckDto };

// ---------- Admin ----------

export interface AdminUserDto {
  id: number;
  telegramId: number;
  username: string | null;
  firstName: string;
  lastName: string | null;
  photoUrl: string | null;
  languageCode: string | null;
  createdAt: number;
  lastSeenAt: number;
  blocked: boolean;
  missedConfirmations: number;
  availableMicro: number;
  frozenMicro: number;
  depositAddresses: { chain: string; address: string; createdAt: number }[];
  stats: {
    depositedMicro: number;
    withdrawnRub: number;
    withdrawnMicro: number;
    withdrawalsTotal: number;
    withdrawalsCompleted: number;
    disputes: number;
    transfersInMicro: number;
    transfersOutMicro: number;
    activeChecksMicro: number;
  };
}

export interface WithdrawalEventDto {
  id: number;
  at: number;
  actor: 'user' | 'admin' | 'system';
  type: string;
  data: Record<string, unknown> | null;
}

export interface AdminWithdrawalListItem {
  id: number;
  status: WithdrawalStatus;
  method: PayoutMethod;
  amountRub: number;
  amountMicro: number;
  destination: string;
  createdAt: number;
  confirmDeadline: number | null;
  user: { id: number; username: string | null; firstName: string };
}

export interface AdminWithdrawalDto extends AdminWithdrawalListItem {
  phone: string | null;
  bankId: string | null;
  bankName: string | null;
  cardNumber: string | null;
  cardBrand: string | null;
  rate: number;
  /** Rapira price the applied rate was derived from. */
  exchangeRate: number | null;
  balanceBeforeMicro: number;
  sentAt: number | null;
  finishedAt: number | null;
  confirmedBy: 'user' | 'auto' | 'admin' | null;
  rejectReason: string | null;
  contactRequestedAt: number | null;
  clientIp: string | null;
  userAgent: string | null;
  platform: string | null;
  events: WithdrawalEventDto[];
  userDetails: AdminUserDto;
  /** Other accounts that withdrew to the same phone or card. */
  sameDestinationUsers: { id: number; username: string | null; firstName: string; withdrawals: number }[];
  recentWithdrawals: AdminWithdrawalListItem[];
  serverNow: number;
}

export interface AdminCounts {
  pending: number;
  sent: number;
  disputed: number;
  completed: number;
  rejected: number;
}
